# Generated by Django 2.2 on 2020-12-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20201225_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message_content',
        ),
    ]
