# Generated by Django 2.2 on 2020-12-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_auto_20201225_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='wall_message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(max_length=255),
        ),
    ]
